config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  root "top#index"
  get "geojson", to: "top#municipality_spot_counts"

  resources :users, only: %i[new create]
  get "login", to: "user_sessions#new"
  post "login", to: "user_sessions#create"
  delete "logout", to: "user_sessions#destroy"

  resources :spots, only: %i[new create] do
    collection do
      get :get_municipalities
      get :select
    end
    resources :posts
  end
  resources :municipalities, only: %i[index]
  resources :images, only: %i[destroy]
end

app/models/spot.rb
class Spot < ApplicationRecord
  validates :name, presence: true, length: { maximum: 255 }
  validates :latitude, presence: true
  validates :longitude, presence: true

  belongs_to :user
  belongs_to :prefecture
  belongs_to :municipality
  has_many :posts, dependent: :destroy

  has_and_belongs_to_many :categories
end

app/controllers/spots_controller.rb
class SpotsController < ApplicationController
  def new
    @spot = Spot.new
  end

  def create
    @spot = current_user.spots.build(spot_params)

    if @spot.save
      redirect_to new_spot_post_path(@spot), success: "スポットが作成されました"
    else
      flash.now[:danger] = "スポットの作成に失敗しました"
      render :new, status: :unprocessable_entity
    end
  end

  def get_municipalities
    prefecture = Prefecture.find(params[:prefecture_id])
    municipalities = prefecture.municipalities.select(:id, :name)
    render json: municipalities
  end

  def select
    @spots = Spot.all
  end

  private

  def spot_params
    params.require(:spot).permit(:name, :latitude, :longitude, :prefecture_id, :municipality_id, category_ids: [])
  end
end

app/views/spots/_created_spot_map.html.erb
<div class="bg-info-subtle">
  <h2 id="registered_spots">A. 登録済みスポットから選ぶ</h2>
  <p>地図上でピンを選択し、「このスポットについて投稿する」ボタンを押してください</p>

  <div id="created_spot_map" class="mx-auto my-3"></div>
</div>

<style>
  #created_spot_map { height: 600px; width: 95%;}
</style>

<script>
  let created_spot_map
  let currentInfoWindow = null;

  function initMap(){
    geocoder = new google.maps.Geocoder();
    // 初期表示の位置とピン
    created_spot_map = new google.maps.Map(document.getElementById('created_spot_map'), {
      center: {lat: 35.6812, lng: 139.7671},
      zoom: 14,
    });

    // Railsから渡されたスポットデータをJSで扱えるようにパース
    const spots = <%= raw @spots.to_json(only: [:id, :latitude, :longitude, :name]) %>;

    // 各スポットにピンを立てる
    spots.forEach((spot) => {
      const marker = new google.maps.Marker({
        position: {lat: parseFloat(spot.latitude), lng: parseFloat(spot.longitude)},
        map: created_spot_map,
        title: spot.name
      });

      // ピンをクリックした時に表示されるInfoWindow
      const infoWindow = new google.maps.InfoWindow({
        content: `
          <div>
            <h5>${spot.name}</h5>
            <a href='/spots/${spot.id}/posts' class="btn btn-outline-info btn-sm">
              投稿一覧を見る
            </a>
            <a href='/spots/${spot.id}/posts/new' class="btn btn-info btn-sm">
              このスポットについて投稿する
            </a>
          </div>
        `
      });

      // ピンがクリックされた時にInfoWindowを開く
      marker.addListener('click', () => {
        // 既に開いているInfoWindowがあれば閉じる
        if (currentInfoWindow) {
          currentInfoWindow.close();
        }

        infoWindow.open({
          anchor: marker,
          map: created_spot_map,
          shouldFocus: false
        });
        // 現在のInfoWindowを保持
        currentInfoWindow = infoWindow;
      });
    });
  }
</script>
<script src="https://maps.googleapis.com/maps/api/js?key=<%= ENV['GOOGLE_MAPS_API_KEY'] %>&callback=initMap" async defer></script>

app/views/spots/_municipality_select.html.erb
<turbo-frame id="municipality_select_frame">
  <label>市町村</label>
  <select name="spot[municipality_id]" id="spot_municipality_id" class="form-control">
    <option value="">市町村を選択</option>
    <% municipalities&.each do |municipality| %>
      <option value="<%= municipality.id %>"><%= municipality.name %></option>
    <% end %>
  </select>
</turbo-frame>

app/views/spots/_spot_block.html.erb
<h3>スポット名: <%= @spot.name %></h3>
<p>
  都道府県: <span class="badge bg-success text-wrap"><%= @spot.prefecture.name %></span>
  市町村: <span class="badge bg-success text-wrap"><%= @spot.municipality.name %></span>
</p>
<p>緯度: <%= @spot.latitude %> 経度: <%= @spot.longitude %></p>
<p>
  カテゴリ: 
  <% @spot.categories&.each do |category| %>
    <span class="badge bg-success text-wrap"><%= category.name %></span>
  <% end %>
</p>

app/views/spots/_spot_form.html.erb
<br>

      <%= form_with model: @spot, local: true, remote: false, class: "new_spot" do |f| %>
         <%= render "shared/error_messages", object: f.object %>
        <div class="mb-3">
          <%= f.label :name %>
          <%= f.text_field :name, class: "form-control" %>
        </div>
        <div class="row">
          <div class="col">
            <%= f.label :latitude %>
          </div>
          <div class="col">
            <%= f.label :longitude %>
          </div>
        </div>
        <div class="row mb-3">
          <div class="col">
            <%= f.number_field :latitude, step: "0.000001", class: "form-control", id: "spot_latitude", readonly: true %>
          </div>
          <div class="col">
            <%= f.number_field :longitude, step: "0.000001", class: "form-control", id: "spot_longitude", readonly: true %>
          </div>
        </div>
        <div class="row mb-3">
          <div class="col">
            <%= f.label :prefecture_id, "都道府県" %>
            <%= f.collection_select :prefecture_id, Prefecture.all, :id, :name,
            {prompt: "都道府県を選択"}, 
            {class: "form-control",  data: { turbo_action: "change", turbo_frame: "municipality_select" }} %>
          </div>
          <div class="col">
            <%= render partial: 'municipality_select', locals: { municipalities: @municipalities } %>
          </div>
        </div>
        <br>
        <h3>カテゴリ</h3>
        <div>
          <%= f.collection_check_boxes :category_ids, Category.all, :id, :name do |b| %>
            <div>
              <%= b.check_box %> <%= b.label %>
            </div>
          <% end %>
        </div>
        <br>
        <%= f.submit nil, class: "btn btn-primary text-center d-grid gap-2 col-6 mx-auto" %>
        <br>
      <% end %>
    

app/views/spots/_spotcreate_map.html.erb
  <div id='map' class="mx-auto my-3"></div>
  <style>
    #map { height: 600px; width: 95%;}
  </style>

  <script>
    let map

    function initMap(){
      geocoder = new google.maps.Geocoder()

      map = new google.maps.Map(document.getElementById('map'), {  // 初期表示の位置とピン
        center: {lat: 35.6812, lng: 139.7671},
        zoom: 14,
      });
      marker = new google.maps.Marker({
        position:  {lat: 35.6812, lng: 139.7671},
        map: map
      });

      map.addListener("click", function(event) {  //  地図上のクリックにより座標を指すするルート
        placeMarker(event.latLng);
        document.getElementById('spot_latitude').value = event.latLng.lat().toFixed(6);
        document.getElementById('spot_longitude').value = event.latLng.lng().toFixed(6);

        codeLatLng(event.latLng);
      });
    }

    function codeAddress(){   // 検索ボックスから座標を指定するルート
      let inputAddress = document.getElementById('address').value;

      geocoder.geocode( { 'address': inputAddress}, function(results, status) {
        if (status == 'OK') {
          map.setCenter(results[0].geometry.location);

          placeMarker(results[0].geometry.location);  // ピンを立てるためのplaceMarkerメソッド実行
          document.getElementById('spot_latitude').value = results[0].geometry.location.lat().toFixed(6);
          document.getElementById('spot_longitude').value = results[0].geometry.location.lng().toFixed(6);

          codeLatLng(results[0].geometry.location);
        }
      });   
    }

    function placeMarker(location) {   // マーカーを新規に設定するメソッド
      if(marker) {
        marker.setMap(null);  //既存のピンを削除
      }
      marker = new google.maps.Marker({
        position: location,
        map: map
      });
    }

    function codeLatLng(latLng) {    //  マーカーの座標から県と市町村を逆引きして自動選択するメソッド
      geocoder.geocode({ "location": latLng }, function(results, status) {
        if (status == "OK" && results[0]) {
          // Geocode結果から市町村を取得
          let addressComponents = results[0].address_components;
          let city = '';
          let municipality = '';
          let administrativeAreaLevel2 = '';  // 郡名
          let locality = '';  // 市町村名
          let sublocalityLevel1 = '';  // 政令指定都市の区名

          // 市町村の情報を抽出
          addressComponents.forEach(function(component) {
            if (component.types.includes('administrative_area_level_1')) {
              prefecture = component.long_name;
            }
            if (component.types.includes('administrative_area_level_2')) {
              administrativeAreaLevel2 = component.long_name;
            }
            if (component.types.includes('locality')) {
              locality = component.long_name;
            }
            if (component.types.includes('sublocality_level_1')) {
              sublocalityLevel1 = component.long_name;
            }
          });

          if (administrativeAreaLevel2) {
            // 郡名 + 市町村名 の場合
            municipality = administrativeAreaLevel2 + locality;
          } else if (sublocalityLevel1) {
            // 市町村名 + 区名 の場合
            municipality = locality + sublocalityLevel1;
          } else {
            // それ以外の場合は普通に市町村名だけ
            municipality = locality;
          }

          display.textContent = prefecture + municipality
          
          // 市町村のフォームに自動入力
          const prefectureId = prefectureMap[prefecture];
          if (prefectureId) {
            document.getElementById('spot_prefecture_id').value = prefectureId;

            const url = `/municipalities?prefecture_id=${prefectureId}`;
            fetch(url, {
              headers: { Accept: "text/vnd.turbo-stream.html" }
            })
            .then((response) => response.text())
            .then((html) => {
              // 市町村リストを更新
              const municipalityFrame = document.querySelector("#municipality_select_frame");
              if (municipalityFrame) {
                municipalityFrame.innerHTML = html;

                // 市町村IDを取得し、自動的に選択
                setTimeout(() => {
                  const municipalityId = municipalityMap[municipality];
                  if (municipalityId) {
                    document.getElementById('spot_municipality_id').value = municipalityId;
                  } else {
                    alert('対応する市区町村が見つかりませんでした');
                  }
                }, 200); // 500ms 待機してから市町村を選択
              } else {
                console.error("municipality_select_frame の要素が見つかりません");
              }
            })
            .catch((error) => {
              console.error("エラーが発生しました:", error);
            });

          } else {
            alert('対応する都道府県が見つかりませんでした');
          }
        } else {
          alert('市町村情報を取得できませんでした');
        }
      });
    }

  </script>
  <script src="https://maps.googleapis.com/maps/api/js?key=<%= ENV['GOOGLE_MAPS_API_KEY'] %>&callback=initMap" async defer></script>

app/views/spots/new.html.erb
<div class="col-lg-8 offset-lg-2">
  <h1>新規投稿 -スポット登録-</h1>
  <br>
  <h5 class="mb-3">
    <li>①②いずれかの方法でスポットの座標を決定してください。</li>
    <p>① 検索ボックスでスポット名称を検索 <span></span>② 地図上で該当する位置をクリック</p>

    <li>ピンの位置に応じて、緯度経度・都道府県・市町村を自動取得します。</li>

    <li>登録するスポット名称、該当するカテゴリをフォームから選択してください。</li>
  </h5>
  <div class="d-flex align-items-center">
    <input id="address" type="textbox" placeholder="スポット名を検索" class="p-1">
    <input type="button" value="検索" onclick="codeAddress()" class="p-1 me-3">
    市区町村の取得結果： <div id="display"></div>
  </div>

  <%= render "spotcreate_map" %>
  <%= render partial: "spot_form" %>
</div>

<script>
  const prefectureMap = {
    <% Prefecture.all.each do |prefecture| %>
      "<%= prefecture.name %>": <%= prefecture.id %>,
    <% end %>
  };

  const municipalityMap = {
    <% Municipality.all.each do |municipality| %>
      "<%= municipality.name %>": <%= municipality.id %>,
    <% end %>
  };
</script>

app/views/spots/select.html.erb
  <div class="row">
    <div class="col-lg-8 offset-lg-2">
      <h1>新規投稿 -スポット選択-</h1>
      <div class="text-center my-4">
        <%= link_to "↓ 登録済みスポットから選ぶ", "#registered_spots", class:"btn btn-primary" %>
        <%= link_to "↓ スポットを新規作成する", "#new_spot", class:"btn btn-warning" %>
      </div>
    
      <%= render "created_spot_map" %>

      <div class="mb-3 bg-warning-subtle">
        <h2 id="new_spot">B. スポットを新規作成する</h2>
        <%= link_to "スポット作成ページはこちら", new_spot_path, data: { turbo: false }, class: "btn btn-primary text-center d-grid gap-2 col-6 mx-auto" %>
      </div>
    </div>
  </div>