config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  root "top#index"
  get "geojson", to: "top#municipality_spot_counts"

  resources :users, only: %i[new create]
  get "login", to: "user_sessions#new"
  post "login", to: "user_sessions#create"
  delete "logout", to: "user_sessions#destroy"

  resources :spots, only: %i[new create] do
    collection do
      get :get_municipalities
      get :select
    end
    resources :posts
  end
  resources :municipalities, only: %i[index]
  resources :images, only: %i[destroy]
end

app/views/shared/_before_login_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg navigation navbar-light bg-success p-2 bg-opacity-75">

    <%= link_to "LocalTripHub", root_path, class: "navbar-brand" %>

    <button class='navbar-toggler' data-bs-toggle='collapse' data-bs-target='#navbarSupportedContent' aria-controls='navbarSupportedContent' aria-expanded='false' aria-label='Toggle navigation'>
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ms-auto main-nav align-items-center">
        <li class="nav-item"><%= link_to t('header.post_map'), "#", class: "nav-link" %></li>
        <li class="nav-item"><%= link_to t('header.login'), login_path, class:"nav-link" %></li>
      </ul>
    </div>
  </nav>
</header>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation" class="alert alert-danger">
    <ul class="mb-0">
      <% object.errors.each do |error| %>
        <li><%= error.full_message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_flash_message.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>">
    <%= message %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer id='footer' class='footer-bottom bg-dark-subtle'>

  <div class="sp">
    <ul class="other d-flex justify-content-center">
      <li class="mx-3"><%= link_to t('footer.privacy_policy'), "#" %></li>  <!-- privacypolicy -->
      <li class="mx-3"><%= link_to t('footer.site_policy'), "#" %></li>  <!-- sitepolicy -->
      <li class="mx-3"><%= link_to t('footer.contact'), "#" %></li>  <!-- contact -->
    </ul>
  </div>
  <div class="text-center">
    <small>© LocalTripHub ALL RIGHTS RESERVED.</small>
  </div>
</footer>

app/views/shared/_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg navigation navbar-light bg-success p-2 bg-opacity-75">

    <%= link_to "LocalTripHub", root_path, data: { turbo: false }, class: "navbar-brand" %>

    <button class='navbar-toggler' data-bs-toggle='collapse' data-bs-target='#navbarSupportedContent' aria-controls='navbarSupportedContent' aria-expanded='false' aria-label='Toggle navigation'>
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ms-auto main-nav align-items-center">
        <li class="nav-item"><%= link_to t('header.create_post'), select_spots_path, data: { turbo: false }, class:"nav-link" %></li>
        <li class="nav-item"><%= link_to t('header.post_map'), "#", class:"nav-link" %></li>
        <li class="nav-item"><%= link_to t('header.bookmarked_list'), "#", class: "nav-link" %></li>
        <li class="nav-item dropdown dropdown-slide">
          <%= link_to current_user.nickname, '#', class: 'nav-link', data: { bs_toggle: 'dropdown' }, aria: { haspopup: 'true', expanded: 'false' }, id: 'header-profile' %>
          <div class="dropdown-menu dropdown-menu-end">
            <%= link_to t('header.mypage'), "#", class:"nav-link dropdown-item" %>
            <%= link_to t('header.logout'), logout_path, class:"nav-link dropdown-item text-danger", data: {turbo_method: :delete} %>
          </div>
        </li>
      </ul>
    </div>
  </nav>
</header>