config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  root "top#index"
  get "geojson", to: "top#municipality_spot_counts"

  resources :users, only: %i[new create]
  get "login", to: "user_sessions#new"
  post "login", to: "user_sessions#create"
  delete "logout", to: "user_sessions#destroy"

  resources :spots, only: %i[new create] do
    collection do
      get :get_municipalities
      get :select
    end
    resources :posts
  end
  resources :municipalities, only: %i[index]
  resources :images, only: %i[destroy]
end

app/models/post.rb
class Post < ApplicationRecord
  validates :content, presence: true, length: { maximum: 65535 }
  validates :access_info, presence: true, length: { maximum: 65535 }

  belongs_to :user
  belongs_to :spot
  has_many :images, dependent: :destroy
  accepts_nested_attributes_for :images, allow_destroy: true
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_spot_and_check_access
  before_action :set_post_and_check_access, only: %i[show edit update destroy]

  def new
    @post = @spot.posts.build
    @post.images.build
  end

  def create
    @post = @spot.posts.build(post_params)
    @post.user = current_user

    if @post.save
      redirect_to spot_posts_path(@spot), success: "投稿が作成されました"
    else
      flash.now[:danger] = "投稿の作成に失敗しました"
      render :new, status: :unprocessable_entity
    end
  end

  def index
    @posts = Post.where(spot_id: params[:spot_id]).order(created_at: :desc).page(params[:page])
  end

  def show; end

  def edit; end

  def update
    if @post.update(post_params)
      redirect_to spot_post_path(@spot), success: "投稿が更新されました"
    else
      flash.now[:danger] = "投稿の更新に失敗しました"
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @post.destroy!
    redirect_to spot_posts_path(@spot), status: :see_other, success: "投稿が削除されました"
  end

  private

  def post_params
    params.require(:post).permit(:access_info, :content, images_attributes: [ :image_url, :image_url_cache ])
  end

  def set_spot_and_check_access
    @spot = Spot.includes(:prefecture, :municipality).find_by(id: params[:spot_id])
    render_404(@spot)
  end

  def set_post_and_check_access
    @post = Post.find_by(id: params[:id])
    render_404(@post)

    if @post.spot_id != @spot.id
      render file: "public/404.html"
    end
  end
end

app/views/posts/_post_block.html.erb
<% if @posts.present? %>
  <% @posts.each do |post| %>
    
      <div class="post-preview d-flex border mb-3" style="height: 205px;" >
        <!-- 画像表示エリア -->
        <div class="image-area d-flex overflow-auto" style="background-color: #f0f0f0; width: 50%; height: 100%; white-space: nowrap;">
          <% post.images&.each do |image| %>
            <% if image.image_url.present? %>
              <div class="image-box mr-2" style="display: inline-block; border: 2px solid #f0f0f0;">
                <%= image_tag image.image_url.url, height: "186px", class: "mr-1" %>
              </div>
            <% end %>
          <% end %>
        </div>

        <!-- テキスト表示エリア -->
        <div class="d-flex flex-column mb-3" style="width: 50%; height: 100%;">
          <div class="d-flex justify-content-between p-2">
            <div>
              <%= post.user.nickname %>
            </div>
            <div>
              <% if current_user.own?(post) %>
                <%= link_to "編集", edit_spot_post_path(post.spot, post), class:"btn btn-sm btn-primary" %>
                <%= link_to "削除", spot_post_path(post.spot, post), data: { turbo_confirm: "削除しますか？", turbo_method: :delete }, class:"btn btn-sm btn-danger" %>
              <% end %>
            <%= l post.created_at %>
            </div>
          </div>

          <div class="mt-2 text-truncate p-2" >
            <%= post.content %>
          </div>
          
          <div class="mt-2 text-truncate p-2">
            <%= post.access_info %>
          </div>
          <div class="d-grid gap-2 col-9 mx-auto">
            <%= link_to "詳細へ", spot_post_path(post.spot, post), class:"btn btn-outline-primary p-2" %>
          </div>
        </div>
      </div>
    
  <% end %>
  <%= paginate @posts, theme: "bootstrap-5" %>
<% else %>
  <p>このスポットに関する投稿はありません</p>
<% end %>

app/views/posts/_post_form.html.erb
  <%= form_with model: [@spot, @post], local: true do |f| %>
    <%= render "shared/error_messages", object: f.object %>
    <div class="mb-3">
      <%= f.label :content %>
      <%= f.text_area :content, class: "form-control", rows: 10 %>
    </div>

    <div class="mb-3">
      <%= f.label :access_info %>
      <%= f.text_area :access_info, class: "form-control", rows: 4 %>
    </div>

    
    <div class="mb-3">
      <%= f.label :image_url %>
      <%= f.file_field :image_url, class: "form-control", accept: 'image/*', multiple: true, name: "post[images_attributes][][image_url]" %>
    </div>
    
    <div class="d-flex">
      <% @post.images&.each do |image| %>
        <% if image.id.present? && image.image_url.present? %>
          <div class="image-box d-inline-block text-center me-2" style="display: border: 2px solid #f0f0f0;">
            <%= image_tag image.image_url.url, height: "186px", class: "mr-1" %>
            <div class="mt-1">
            <%= link_to '削除', image_path(image), data: { turbo_confirm: "画像を削除しますか？ (直ちに削除が行われます)", turbo_method: :delete}, class: 'btn btn-danger' %>
            </div>
          </div>
        <% end %>
      <% end %>
      
    </div>
    <br>
  
    <%= f.submit nil, class: "btn btn-primary" %>
  <% end %>
  <br>

app/views/posts/edit.html.erb
<div class="col-lg-8 offset-lg-2">
  <h1>投稿編集<h1>

  <%= render "spots/spot_block" %>

  <%= render "post_form" %>
</div>

app/views/posts/index.html.erb
<div class="col-lg-8 offset-lg-2">
  <h1>投稿一覧<h1>

  <%= render "spots/spot_block" %>

  <%= render "posts/post_block" %>

  <div class="d-grid gap-2 col-6 mx-auto mb-3">
    <%= link_to "このスポットについて新規投稿する", new_spot_post_path(@spot), class: "btn btn-primary" %>
  </div>
</div>

app/views/posts/new.html.erb
<div class="col-lg-8 offset-lg-2">
  <h1>投稿作成<h1>

  <%= render "spots/spot_block" %>

  <%= render "post_form" %>
</div>

app/views/posts/show.html.erb
<div class="col-lg-8 offset-lg-2">
  <h1>投稿詳細<h1>
  
  <%= render "spots/spot_block" %>

  <div class="d-flex justify-content-between p-2">
    <div>
      <%= @post.user.nickname %>
    </div>
    <div>
      <% if current_user.id === @post.user_id %>
        <%= link_to "編集", edit_spot_post_path(@post.spot, @post), class:"btn btn-sm btn-primary" %>
        <%= link_to "削除", spot_post_path(@post.spot, @post), data: { turbo_confirm: "削除しますか？", turbo_method: :delete }, class:"btn btn-sm btn-danger" %>
      <% end %>
      <%= l @post.created_at %>
    </div>
  </div>
  <div class="d-flex flex-wrap gap-3">
    <% @post.images&.each do |image| %>
      <% if image.image_url.present? %>
        <div class="p-0">
          <%= image_tag image.image_url.url, height: "240px", class: "mr-1" %>
        </div>
      <% end%>
    <% end%>
  </div>

  <h5 class="fw-semibold">見どころ・感想など</h5>
  <div class="border border-2 p-2">
    <%= simple_format(@post.content) %>
  </div>
  <br>
  <h5 class="fw-semibold">アクセス・営業時間</h5>
  <div class="border border-2 p-2">
    <%= simple_format(@post.access_info) %>
  </div>
  <br>
</div>