config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  root "top#index"
  get "geojson", to: "top#municipality_spot_counts"

  resources :users, only: %i[new create]
  get "login", to: "user_sessions#new"
  post "login", to: "user_sessions#create"
  delete "logout", to: "user_sessions#destroy"

  resources :spots, only: %i[new create] do
    collection do
      get :get_municipalities
      get :select
    end
    resources :posts
  end
  resources :municipalities, only: %i[index]
  resources :images, only: %i[destroy]
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  skip_before_action :require_login, only: %i[new create]

  def new; end

  def create
    @user = login(params[:email], params[:password])

    if @user
      redirect_to root_path, success: t("user_sessions.create.success")
    else
      flash.now[:danger] = t("user_sessions.create.failure")
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    logout
    redirect_to root_path, status: :see_other, success: t("user_sessions.destroy.success")
  end
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/views/user_sessions/new.html.erb
<div class="container">
  <div class="row">
    <div class=" col-md-10 col-lg-8 mx-auto">
      <h1><%= t('.title') %></h1>
      <%= form_with url: login_path do |f| %>
        <div class="mb-3">
          <%= f.label :email %>
          <%= f.email_field :email, class: "form-control" %>
        </div>
        <div class="mb-3">
          <%= f.label :password %>
          <%= f.password_field :password, class: "form-control" %>
        </div>
        <div class="d-flex justify-content-center">
        <%= f.submit t('.login'), class: "btn btn-primary w-50" %>
        </div>
      <% end %>
      <br>
      <div class='text-center'>
        <%= link_to t('.to_register_page'), new_user_path %>
        <br>
        <%= link_to t('.password_forget'), '#' %>
      </div>
      <br>
    </div>
  </div>
</div>